### ISSUE TITLE
580k db gone

### ISSUE THREAD

**Issue by xsoft** [MellowYarker/Observer#58]
I guess that after 2-3 years the init DB dump is gone.
( https://observer-test-bucket.s3.amazonaws.com/sql/result_##.sql )

**Comment by cacheburner** [comment]
Yeah, I was getting charged by AWS for storage fee's and figured no one would actually use this. Turned out the storage was allocated by an EC2 instance rather than this S3 bucket, so technically it could have stuck around (the AWS console confused me)...

Was there any particular reason you were interested in the data? I can take a look at this tomorrow and maybe help you out.

As a side note, the blockchain has grown substantially since the last update of this DB. If you really want (un)spent tx data, there are much better resources for acquiring that, I can provide a few links later today.

**Comment by xsoft** [comment]
Thanks. I am fine without those data.
I was just wondering if it isn't caused by some trivial issue like URL change.
